const enum BurmType {
  TEXT = "TEXT",
  INTEGER = "INTEGER",
  BOOLEAN = "BOOLEAN",
  STRING = "STRING",
  SMALLINT = "SMALLINT",
  BIGINT = "BIGINT",
  DECIMAL = "DECIMAL",
  DATE = "DATE",
  TIME = "TIME",
  DATETIME = "DATETIME",
  DATETIMEZONE = "DATETIMEZONE",
  OBJECT = "OBJECT",
  ARRAY = "ARRAY",
  FLOAT = "FLOAT",
  GUID = "GUID",
  STREAM = "STREAM",
}

export default BurmType;
